#!/usr/bin/env node
// Zero-dependency test for the Worker's scraping/parsing port.
//
//   node worker/test.js
//
// Runs the Worker's pure functions (imported straight from src/index.js)
// against real pages and PDFs saved in testdata/, and asserts the output
// matches testdata/reference.json — which was generated by running
// sources.py on the very same inputs. Green here means the Worker
// produces byte-identical normalized sheet text to the Python proxy.
//
// To regenerate reference.json after changing sources.py, see
// tools notes in README.md.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { copperknob, linedancerweb, pdfToText, composeSheetText, htmlUnescape, clean }
  from "./src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const td = (name) => join(here, "testdata", name);
const reference = JSON.parse(readFileSync(td("reference.json"), "utf-8"));

let passed = 0, failed = 0;

function check(name, actual, expected) {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    passed++;
    console.log("  ok  " + name);
  } else {
    failed++;
    console.log("FAIL  " + name);
    // show the first divergence to keep failures readable
    const as = typeof actual === "string" ? actual : a;
    const es = typeof expected === "string" ? expected : e;
    let i = 0;
    while (i < Math.min(as.length, es.length) && as[i] === es[i]) i++;
    console.log("      first difference at char " + i + ":");
    console.log("      js: " + JSON.stringify(as.slice(Math.max(0, i - 40), i + 40)));
    console.log("      py: " + JSON.stringify(es.slice(Math.max(0, i - 40), i + 40)));
  }
}

// --- unit sanity: the Python-compat helpers --------------------------------

check("htmlUnescape numeric + named",
  htmlUnescape("R&amp;B &ndash; caf&eacute; &#8217;n&#x2019; &nbsp;&frac12; &amp"),
  "R&B – café ’n’  ½ &");
check("htmlUnescape cp1252 charref quirk", htmlUnescape("&#151;&#146;"), "—’");
check("clean collapses python whitespace",
  clean("a  b <b>c</b>  d\n"), "a b c d");

// --- CopperKnob: search-page parsing and sheet normalization ---------------

check("copperknob search parse (havana)",
  copperknob.parseSearch(readFileSync(td("ck-search-havana.html"), "utf-8")),
  reference.ck_search);

for (const [name, url] of [
  ["choosin-texas", "https://www.copperknob.co.uk/stepsheets/LRV9X25/choosin-texas"],
  ["havana-cha", "https://www.copperknob.co.uk/stepsheets/XDDP9R6/havana-cha"],
]) {
  check("copperknob sheet parse (" + name + ")",
    copperknob.parseSheet(readFileSync(td("ck-sheet-" + name + ".html"), "utf-8"), url),
    reference["ck_sheet_" + name]);
}

// --- Linedancer: search, dance page, PDF extraction, full sheet ------------

check("linedancer search parse (islands)",
  linedancerweb.parseSearch(readFileSync(td("lw-search-islands.html"), "utf-8")),
  reference.lw_search);

for (const did of ["19177", "19175"]) {
  const ref = reference["lw_" + did];
  const page = readFileSync(td("lw-dance-" + did + ".html"), "utf-8");
  const { fields, title } = linedancerweb.parseDancePage(page);
  check("linedancer dance page fields (" + did + ")", { fields, title },
    { fields: ref.fields, title: ref.title });

  const pdf = new Uint8Array(readFileSync(td("lw-" + did + ".pdf")));
  const text = await pdfToText(pdf);
  check("pdf extract (" + did + ")", text, ref.pdf_text);

  const body = linedancerweb.normalizeBody(text, title);
  const sheet = {
    title,
    url: "https://www.linedancerweb.com/dance.php?id=" + did,
    text: composeSheetText(title || "Linedancer dance", fields, body),
  };
  check("linedancer full sheet (" + did + ")", sheet, ref.sheet);
}

// --- PDF corner cases the real corpus lacks (synthetic, verified against
// --- sources.py output): ASCII85+Flate chains and /ObjStm + ToUnicode CMaps

check("pdf extract (synthetic ascii85 chain, bare-\\r stream)",
  await pdfToText(new Uint8Array(readFileSync(td("synth-a85.pdf")))),
  reference.synth_a85);
check("pdf extract (synthetic objstm + cmap)",
  await pdfToText(new Uint8Array(readFileSync(td("synth-objstm.pdf")))),
  reference.synth_objstm);

console.log("\n" + passed + " passed, " + failed + " failed");
process.exit(failed ? 1 : 0);
